services:
  ecommerce_pg:
    container_name: ecommerce_pg
    image: postgres:latest
    restart: always
    env_file:
      - docker.env
    ports:
      - "5432:5432"

  ecommerce_redis:
    container_name: ecommerce_redis
    image: redis:alpine
    env_file:
      - docker.env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
