services:

  ecommerce_backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - ecommerce_pg
      - ecommerce_redis
    networks:
      - ecommerce-network

  ecommerce_pg:
    container_name: ecommerce_pg
    image: postgres:latest
    restart: always
    env_file:
      - docker.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - ecommerce-network

  ecommerce_redis:
    container_name: ecommerce_redis
    image: redis:alpine
    env_file:
      - docker.env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - ecommerce-network

  ecommerce_minio:
    image: docker.io/bitnami/minio:2022
    env_file:
      - docker.env
    ports:
      - "9000:9000"
      - "9001:9001"
    platform: linux/amd64

    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge